# Generated by Django 5.2.10 on 2026-01-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_seats',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
