# Generated by Django 5.2.10 on 2026-01-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='circuit_image',
            field=models.ImageField(blank=True, null=True, upload_to='circuits/'),
        ),
    ]
